name := "pdsdk"
name-lib := "libpdsdk"

build-ios:
    just build-ios-target aarch64-apple-ios
    just build-ios-target aarch64-apple-ios-sim 
    just build-ios-target x86_64-apple-ios
    just build-ios-bindings

build-ios-target target:
    cargo build --target {{target}} --release
    @ls -lh target/{{target}}/release/lib* | awk '{print $9, $5}' | column -t -s " " 

build-ios-bindings:
    cargo run --features bindgen --bin bindgen generate --library target/aarch64-apple-ios-sim/release/{{name-lib}}.a --language swift --out-dir target/bindings/ios
