name: Example app integration builds

on:
  push:
    branches: ["main"]
    paths:
      - "apps/**"
      - "justfile"
      - "native/pdsdkd/src/lib.rs"
      - "pkgs/**"
  pull_request:
    branches: ["main"]
    paths:
      - "apps/**"
      - "justfile"
      - "native/pdsdkd/src/lib.rs"
      - "pkgs/**"

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        platform: [android, ios, web]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v3

      - name: Cache brew (this might include Android SDKs)
        uses: actions/cache@v4
        with:
          path: |
            /opt/homebrew
            ~/.cargo/bin
          key: ${{ runner.os }}-${{ matrix.platform }}-homebrew-${{ hashFiles('justfile') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.platform }}-homebrew-

      - name: Cache rust toolchains
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: ${{ runner.os }}-${{ matrix.platform }}-rustup-${{ hashFiles('native/rust-toolchain.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.platform }}-rustup-

      - name: Cache rust / cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            native/target
          key: ${{ runner.os }}-${{ matrix.platform }}-cargo-${{ hashFiles('native/Cargo.lock', 'native/rust-toolchain.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.platform }}-cargo-

      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            pkgs/aar/.gradle
            apps/android/.gradle
          key: ${{ runner.os }}-${{ matrix.platform }}-gradle-${{ hashFiles('pkgs/aar/gradle/wrapper/gradle-wrapper.properties', 'apps/android/gradle/wrapper/gradle-wrapper.properties', 'pkgs/aar/build.gradle*', 'apps/android/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.platform }}-${{ matrix.platform }}-gradle-

      - name: Install development dependencies for ${{ matrix.platform }}
        run: just deps-${{ matrix.platform }}

      - name: Build and test native bindings for ${{ matrix.platform }}
        run: just build-${{ matrix.platform }}
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false

      - name: Debug on failure
        if: failure()
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
          detached: true
        timeout-minutes: 15
